{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "962b77bb",
   "metadata": {},
   "source": [
    "## [Knowledge 1.]: Two Pointers\n",
    "\n",
    "### What Is the Two Pointer Technique?\n",
    "\n",
    "The **two pointer technique** is a common algorithmic pattern used to traverse arrays, strings, or linked lists with two indices (or \"pointers\") that move through the data structure — either **inward from both ends**, **in the same direction**, or sometimes **at different speeds**.\n",
    "\n",
    "It helps reduce nested loops (O(n²)) into more efficient **O(n)** time complexity.\n",
    "\n",
    "---\n",
    "how to use it in most cases:\n",
    "```python\n",
    "left = 0\n",
    "right = len(n) - 1\n",
    "while left < right:\n",
    "    then do something here\n",
    "    left += 1\n",
    "    right -= 1\n",
    "```\n",
    "---\n",
    "\n",
    "### Types of Two Pointer Patterns\n",
    "\n",
    "| Pattern            | Description                                       | Example Problem                              |\n",
    "|--------------------|---------------------------------------------------|----------------------------------------------|\n",
    "| Opposite Direction | One pointer from start, one from end              | Check if a word is a palindrome              |\n",
    "| Same Direction     | Both pointers move right, often to maintain a window | Longest Substring Without Repeating Characters |\n",
    "| Fast & Slow        | One pointer moves faster than the other           | Detecting a cycle in a linked list           |\n",
    "\n",
    "---\n",
    "\n",
    "### Basic Implementation Example: Is Palindrome\n",
    "\n",
    "```python\n",
    "def is_palindrome(s: str) -> bool:\n",
    "    left = 0\n",
    "    right = len(s) - 1\n",
    "\n",
    "    while left < right:\n",
    "        if s[left] != s[right]:\n",
    "            return False\n",
    "        left += 1\n",
    "        right -= 1\n",
    "    return True\n",
    "    ```\n",
    "\n",
    "Key Steps:\n",
    "\n",
    "- Start with two pointers: left = 0, right = len(s) - 1\n",
    "\n",
    "- Compare characters at each end\n",
    "\n",
    "- If they match, move left rightward and right leftward\n",
    "\n",
    "- If not, return False\n",
    "\n",
    "- If the loop finishes, return True\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
